<template>
  <div class="reconciliation-page">
    <header class="page-header">
      <h1>Reconciliation Exports</h1>
      <router-link to="/" class="back-link">Back to Dashboard</router-link>
    </header>

    <main class="content">
      <div v-if="error" class="error-message">{{ error }}</div>
      <div v-if="successMsg" class="success-message">{{ successMsg }}</div>

      <!-- Run Export -->
      <div class="card">
        <h2>Generate Export</h2>
        <p class="hint">
          Run a reconciliation export for a specific business date. Exports include all completed and
          voided transactions for the selected date.
        </p>
        <form @submit.prevent="handleRunExport" class="export-form">
          <div class="form-group">
            <label for="businessDate">Business Date</label>
            <input id="businessDate" v-model="exportDate" type="date" required />
          </div>
          <button type="submit" class="primary-btn" :disabled="exporting || !exportDate">
            {{ exporting ? 'Exporting...' : 'Run Export' }}
          </button>
        </form>
      </div>

      <!-- Export History -->
      <div class="card">
        <h2>Export History</h2>
        <div v-if="loading" class="loading">Loading exports...</div>
        <table v-else-if="exports.length">
          <thead>
            <tr>
              <th>Business Date</th>
              <th>Version</th>
              <th>Transactions</th>
              <th>Completed Total</th>
              <th>Voided Total</th>
              <th>Generated By</th>
              <th>Generated At</th>
              <th>File</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="exp in exports" :key="exp.id">
              <td>{{ exp.businessDate }}</td>
              <td>v{{ exp.exportVersion }}</td>
              <td>{{ exp.transactionCount }}</td>
              <td class="amount">${{ Number(exp.totalCompletedAmount).toFixed(2) }}</td>
              <td class="amount voided">${{ Number(exp.totalVoidedAmount).toFixed(2) }}</td>
              <td>{{ exp.generatedBy }}</td>
              <td>{{ formatDate(exp.generatedAt) }}</td>
              <td class="file-path" :title="exp.filePath">{{ exp.filePath }}</td>
            </tr>
          </tbody>
        </table>
        <p v-else class="empty-state">No reconciliation exports yet.</p>
      </div>
    </main>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import * as reconciliationApi from '@/api/reconciliation'
import type { ReconciliationExport } from '@/api/reconciliation'

const exports = ref<ReconciliationExport[]>([])
const loading = ref(false)
const error = ref<string | null>(null)
const successMsg = ref<string | null>(null)
const exporting = ref(false)

const today = new Date().toISOString().split('T')[0]
const exportDate = ref(today)

onMounted(loadExports)

async function loadExports() {
  loading.value = true
  error.value = null
  try {
    const page = await reconciliationApi.listExports()
    exports.value = page.content
  } catch (e: any) {
    error.value = e.message ?? 'Failed to load exports'
  } finally {
    loading.value = false
  }
}

async function handleRunExport() {
  if (!exportDate.value) return
  exporting.value = true
  error.value = null
  successMsg.value = null
  try {
    const result = await reconciliationApi.triggerExport(exportDate.value)
    successMsg.value = `Export generated for ${result.businessDate} (v${result.exportVersion}, ${result.transactionCount} transactions)`
    await loadExports()
    setTimeout(() => { successMsg.value = null }, 5000)
  } catch (e: any) {
    error.value = e.message ?? 'Export failed'
  } finally {
    exporting.value = false
  }
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString(undefined, {
    month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit',
  })
}
</script>

<style scoped>
.reconciliation-page { min-height: 100vh; background: #f5f5f5; }
.page-header {
  display: flex; justify-content: space-between; align-items: center;
  padding: 1rem 2rem; background: white; box-shadow: 0 1px 3px rgba(0,0,0,0.1);
}
.page-header h1 { font-size: 1.3rem; color: #333; }
.back-link { color: #667eea; text-decoration: none; }
.content { padding: 2rem; max-width: 1100px; margin: 0 auto; }
.card {
  background: white; padding: 1.5rem; border-radius: 8px;
  box-shadow: 0 1px 3px rgba(0,0,0,0.08); margin-bottom: 1.5rem;
}
.card h2 { margin-bottom: 1rem; font-size: 1.1rem; }
.hint { font-size: 0.9rem; color: #666; margin-bottom: 1rem; }

.export-form { display: flex; gap: 1rem; align-items: flex-end; }
.form-group { display: flex; flex-direction: column; }
.form-group label { font-size: 0.85rem; color: #555; margin-bottom: 0.3rem; font-weight: 500; }
.form-group input {
  padding: 0.5rem; border: 1px solid #ddd; border-radius: 6px; font-size: 0.95rem;
}
.primary-btn {
  padding: 0.5rem 1.5rem; background: #667eea; color: white;
  border: none; border-radius: 6px; cursor: pointer; font-size: 0.9rem;
}
.primary-btn:disabled { opacity: 0.6; cursor: not-allowed; }

table { width: 100%; border-collapse: collapse; }
th, td { padding: 0.6rem; text-align: left; border-bottom: 1px solid #eee; font-size: 0.85rem; }
th { font-weight: 600; color: #555; }
.amount { font-family: monospace; }
.amount.voided { color: #dc3545; }
.file-path { max-width: 180px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; font-family: monospace; font-size: 0.75rem; color: #666; }

.loading { text-align: center; padding: 2rem; color: #666; }
.error-message { background: #fee; color: #c00; padding: 0.6rem; border-radius: 6px; margin-bottom: 1rem; }
.success-message { background: #d4edda; color: #155724; padding: 0.6rem; border-radius: 6px; margin-bottom: 1rem; }
.empty-state { color: #999; text-align: center; padding: 2rem; }
</style>
